default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_stripe_development

test:
  <<: *default
  database: rails_stripe_test

production:
  <<: *default
  database: rails_stripe_production
  username: rails_stripe
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
